app1/urls.py
from django.urls import path
from app1.views import *
app_name='raji'

urlpatterns=[
    path('teja1/',teja1,name='teja1'),

]

app2/urls.py
from django.urls import path
from app2.views import *
app_name='shankar'

urlpatterns=[
    path('teja2/',teja2,name='teja2'),
]

project33/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2
urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def teja1(request):
    return render(request,'teja1.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def teja2(request):
    return render(request,'teja2.html')

templates/teja1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>teja1</h1>
        <h1>tomorrow new year starts</h1>
        <a href="{% url 'shankar:teja2' %}">click here to go teja2</a>
    </center>
</body>
</html>

templates/teja2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>teja2</h1>
        <h2>we will start new days</h2>
        <a href="{% url 'raji:teja1' %}">click here to go to teja1</a>
    </center>
</body>
</html>